deployInfra:
  enabled: false
  storageAccount: false
  aiSearchService: false
  azureSpeechService: false
  containerRegistry: false
  appServicePremiumPlan: false
  appServiceBasicPlan: false
  eventHubService: false
  azureOpenAIService: false

envCreation:
  enabled: true

midentityCreation: 
  enabled: false

buildPushImages:
  enabled: false
  buildImages: false
  pushImages: false

deployAppService:
  enabled: false

deployContainerApps:
  enabled: false