deployInfra:
  enabled: false
  storageAccount: false
  aiSearchService: true
  azureSpeechService: false
  containerRegistry: false
  appServicePremiumPlan: false
  appServiceBasicPlan: false
  eventHubService: false
  azureOpenAIService: false

envCreation:
  enabled: false

midentityCreation: 
  enabled: false

buildAndPushImagesToACR:
  enabled: false
  buildMainApp: false
  buildIngestionConsumer: false

deployAppService:
  enabled: false

deployContainerApps:
  enabled: true